// @ts-nocheck -- Hono's generic D1 inference is validated by Wrangler's deployment build.
import { Hono } from "hono";
import { getCookie, setCookie } from "hono/cookie";
import { createRemoteJWKSet, jwtVerify } from "jose";
import { lifecycleSchema, moderationSchema, patchDraftSchema, patchItemsSchema, resolutionSchema } from "@hbc/shared";

type RateLimiter = { limit(input: { key: string }): Promise<{ success: boolean }> };
type Env = { DB: D1Database; ASSETS: Fetcher; ENVIRONMENT: string; ADMIN_ORIGIN: string; TEAM_DOMAIN: string; POLICY_AUD: string; ADMIN_AUDIT_HASH_SECRET: string; ADMIN_LIMIT: RateLimiter };
type Vars = { requestId: string; actorHash: string; csrf: string };
type Bindings = { Bindings: Env; Variables: Vars };
const app = new Hono<Bindings>(); const enc = new TextEncoder();
const now = () => new Date().toISOString();
const hex = (bytes: Uint8Array) => [...bytes].map(x => x.toString(16).padStart(2,"0")).join("");
async function sha(value: string | ArrayBuffer) { return hex(new Uint8Array(await crypto.subtle.digest("SHA-256", typeof value === "string" ? enc.encode(value) : value))); }
async function hmac(secret:string,value:string){const key=await crypto.subtle.importKey("raw",enc.encode(secret),{name:"HMAC",hash:"SHA-256"},false,["sign"]);return hex(new Uint8Array(await crypto.subtle.sign("HMAC",key,enc.encode(value))))}
function data<T>(c:any,value:T,status=200){return c.json({data:value,error:null,requestId:c.get("requestId")},status)}
function error(c:any,status:number,code:string,message:string){return c.json({data:null,error:{code,message},requestId:c.get("requestId")},status)}
function originOk(c:any){const origin=c.req.header("origin");return !origin||origin===c.env.ADMIN_ORIGIN||(c.env.ENVIRONMENT==="local"&&/^http:\/\/localhost:\d+$/.test(origin))}
async function audit(c:any,action:string,targetType:string,targetId:string,state:unknown){await c.env.DB.prepare("INSERT INTO admin_audit_logs (admin_actor_hash, action, target_type, target_id, state_json, request_id, created_at) VALUES (?, ?, ?, ?, ?, ?, ?)").bind(c.get("actorHash"),action,targetType,targetId,JSON.stringify(state).slice(0,2000),c.get("requestId"),now()).run()}
async function timeline(db:D1Database,caseId:number,type:string,key:string,publicEvent=true,metadata:unknown={}){await db.prepare("INSERT OR IGNORE INTO timeline_events (case_id,event_type,event_key,is_public,actor_type,metadata_json,created_at) VALUES (?, ?, ?, ?, 'admin', ?, ?)").bind(caseId,type,key,publicEvent?1:0,JSON.stringify(metadata).slice(0,1000),now()).run()}

app.use("*",async(c,next)=>{
  c.set("requestId",crypto.randomUUID()); let subject="local-operator";
  if(c.env.ENVIRONMENT!=="local"){
    const token=c.req.header("Cf-Access-Jwt-Assertion");if(!token)return error(c,401,"ACCESS_REQUIRED","운영자 인증이 필요합니다.");
    try{const jwks=createRemoteJWKSet(new URL(`${c.env.TEAM_DOMAIN}/cdn-cgi/access/certs`));const verified=await jwtVerify(token,jwks,{issuer:c.env.TEAM_DOMAIN,audience:c.env.POLICY_AUD});subject=verified.payload.sub??"unknown"}catch{return error(c,403,"ACCESS_REJECTED","운영자 인증을 확인할 수 없습니다.")}
  }
  const actorHash=await hmac(c.env.ADMIN_AUDIT_HASH_SECRET||"local-audit",subject);c.set("actorHash",actorHash);
  if(c.env.ENVIRONMENT!=="local"&&!(await c.env.ADMIN_LIMIT.limit({key:actorHash})).success)return error(c,429,"RATE_LIMITED","관리 요청이 너무 빠릅니다.");
  let csrf=getCookie(c,"hbc_admin_csrf");if(!csrf){csrf=crypto.randomUUID();setCookie(c,"hbc_admin_csrf",csrf,{httpOnly:false,secure:c.env.ENVIRONMENT!=="local",sameSite:"Strict",path:"/",maxAge:43200})}c.set("csrf",csrf);
  if(!["GET","HEAD","OPTIONS"].includes(c.req.method)){if(!originOk(c)||c.req.header("X-HBC-CSRF")!==csrf)return error(c,403,"CSRF_REJECTED","관리 요청 검증에 실패했습니다.")}
  await next();c.header("X-Content-Type-Options","nosniff");c.header("Referrer-Policy","no-referrer");c.header("X-Robots-Tag","noindex, nofollow");c.header("Content-Security-Policy","default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; base-uri 'none'; frame-ancestors 'none'");
});

function mapCase(r:Record<string,any>){return{id:r.id,caseNumber:r.case_number,title:r.title,reproductionSteps:r.reproduction_steps,expectedResult:r.expected_result,actualResult:r.actual_result,environment:r.environment,severity:r.severity,category:r.category,evidenceEmoji:r.evidence_emoji,moderationStatus:r.moderation_status,visibilityStatus:r.visibility_status,lifecycleStatus:r.lifecycle_status,resolutionCode:r.resolution_code,officialComment:r.official_comment,moderationNote:r.moderation_note,reproductionCount:r.reproduction_count,createdAt:r.created_at,publishedAt:r.published_at,analysis:r.department?{department:r.department,initialGrade:r.initial_grade,workaround:r.workaround,expectedVersion:r.expected_version,bureaucracyWasteIndex:r.bureaucracy_waste_index}:undefined}}
function mapPatch(r:Record<string,any>){return{id:r.id,slug:r.slug,title:r.title,introduction:r.introduction,status:r.status,createdAt:r.created_at,publishedAt:r.published_at}}

app.get("/api/v1/admin/health",c=>data(c,{ok:true,version:"0.1.0"}));
app.get("/api/v1/admin/cases",async c=>{const moderation=c.req.query("moderation")??"pending";let sql="SELECT * FROM cases";const binds:any[]=[];if(moderation!=="all"){sql+=" WHERE moderation_status = ?";binds.push(moderation)}sql+=" ORDER BY created_at, id LIMIT 100";const rows=await c.env.DB.prepare(sql).bind(...binds).all();return data(c,{items:rows.results.map(mapCase),csrfToken:c.get("csrf")})});
app.get("/api/v1/admin/cases/:caseNumber",async c=>{const row=await c.env.DB.prepare("SELECT c.*,a.department,a.initial_grade,a.workaround,a.expected_version,a.bureaucracy_waste_index FROM cases c JOIN case_analyses a ON a.case_id=c.id WHERE c.case_number=?").bind(c.req.param("caseNumber")).first<Record<string,any>>();if(!row)return error(c,404,"NOT_FOUND","사건을 찾지 못했습니다.");const events=await c.env.DB.prepare("SELECT event_type,created_at FROM timeline_events WHERE case_id=? ORDER BY created_at,id").bind(row.id).all();return data(c,{item:{...mapCase(row),timeline:events.results.map(x=>({eventType:x.event_type,createdAt:x.created_at}))},csrfToken:c.get("csrf")})});
app.put("/api/v1/admin/cases/:caseNumber/og-image",async c=>uploadOg(c,"case"));
app.patch("/api/v1/admin/cases/:caseNumber/moderation",async c=>{const parsed=moderationSchema.safeParse(await c.req.json().catch(()=>null));if(!parsed.success)return error(c,400,"INVALID_BODY","검토 작업을 확인하십시오.");const row=await c.env.DB.prepare("SELECT id,moderation_status,visibility_status FROM cases WHERE case_number=?").bind(c.req.param("caseNumber")).first<any>();if(!row)return error(c,404,"NOT_FOUND","사건을 찾지 못했습니다.");const action=parsed.data.action;let moderation=row.moderation_status,visibility=row.visibility_status,event="",publicEvent=true;if(action==="approve"){if(moderation!=="pending")return error(c,409,"INVALID_TRANSITION","대기 사건만 승인할 수 있습니다.");const og=await c.env.DB.prepare("SELECT 1 FROM og_assets WHERE case_id=?").bind(row.id).first();if(!og)return error(c,409,"OG_REQUIRED","공개 전에 OG 이미지를 생성하십시오.");moderation="approved";visibility="public";event="PUBLIC_APPROVED"}else if(action==="reject"){if(moderation!=="pending")return error(c,409,"INVALID_TRANSITION","대기 사건만 반려할 수 있습니다.");moderation="rejected";visibility="hidden";event="REJECTED";publicEvent=false}else if(action==="hide"){if(visibility!=="public")return error(c,409,"INVALID_TRANSITION","공개 사건만 숨길 수 있습니다.");visibility="hidden";event="PUBLIC_HIDDEN"}else if(action==="restore"){if(moderation!=="approved"||visibility!=="hidden")return error(c,409,"INVALID_TRANSITION","승인 후 숨김 사건만 복원할 수 있습니다.");visibility="public";event="PUBLIC_RESTORED"}else{if(moderation!=="rejected")return error(c,409,"INVALID_TRANSITION","반려 사건만 대기로 되돌릴 수 있습니다.");moderation="pending";visibility="pending";event="REJECTION_REVOKED";publicEvent=false}const time=now();await c.env.DB.prepare("UPDATE cases SET moderation_status=?,visibility_status=?,moderation_note=?,published_at=CASE WHEN ?='public' AND published_at IS NULL THEN ? ELSE published_at END,updated_at=? WHERE id=?").bind(moderation,visibility,parsed.data.reason??null,visibility,time,time,row.id).run();await timeline(c.env.DB,row.id,event,`${event.toLowerCase()}-${time}`,publicEvent,{reason:parsed.data.reason});await audit(c,"case.moderation","case",c.req.param("caseNumber"),{action,moderation,visibility});return data(c,{ok:true})});
app.patch("/api/v1/admin/cases/:caseNumber/lifecycle",async c=>{const parsed=lifecycleSchema.safeParse(await c.req.json().catch(()=>null));if(!parsed.success)return error(c,400,"INVALID_BODY","처리 단계를 확인하십시오.");const row=await c.env.DB.prepare("SELECT id,lifecycle_status FROM cases WHERE case_number=?").bind(c.req.param("caseNumber")).first<any>();if(!row)return error(c,404,"NOT_FOUND","사건을 찾지 못했습니다.");if(row.lifecycle_status==="closed")return error(c,409,"REOPEN_REQUIRED","종료 사건은 재검토 절차가 필요합니다.");await c.env.DB.prepare("UPDATE cases SET lifecycle_status=?,updated_at=? WHERE id=?").bind(parsed.data.lifecycleStatus,now(),row.id).run();const type=parsed.data.lifecycleStatus==="reviewing"?"REVIEW_STARTED":"REVIEW_RETURNED_TO_OPEN";await timeline(c.env.DB,row.id,type,`${type.toLowerCase()}-${Date.now()}`);await audit(c,"case.lifecycle","case",c.req.param("caseNumber"),parsed.data);return data(c,{ok:true})});
app.put("/api/v1/admin/cases/:caseNumber/resolution",async c=>{const parsed=resolutionSchema.safeParse(await c.req.json().catch(()=>null));if(!parsed.success)return error(c,400,"INVALID_BODY","판정과 공식 의견을 확인하십시오.");const row=await c.env.DB.prepare("SELECT id,title,visibility_status FROM cases WHERE case_number=?").bind(c.req.param("caseNumber")).first<any>();if(!row)return error(c,404,"NOT_FOUND","사건을 찾지 못했습니다.");let duplicateId:null|number=null;if(parsed.data.resolutionCode==="DUPLICATE"){if(!parsed.data.duplicateOfCaseNumber||parsed.data.duplicateOfCaseNumber===c.req.param("caseNumber"))return error(c,400,"DUPLICATE_TARGET_REQUIRED","다른 공개 기준 사건이 필요합니다.");const dup=await c.env.DB.prepare("SELECT id FROM cases WHERE case_number=? AND visibility_status='public'").bind(parsed.data.duplicateOfCaseNumber).first<{id:number}>();if(!dup)return error(c,400,"INVALID_DUPLICATE_TARGET","공개 기준 사건을 찾지 못했습니다.");duplicateId=dup.id}const time=now();await c.env.DB.prepare("UPDATE cases SET lifecycle_status='closed',resolution_code=?,official_comment=?,duplicate_of_case_id=?,resolved_at=?,updated_at=? WHERE id=?").bind(parsed.data.resolutionCode,parsed.data.officialComment,duplicateId,time,time,row.id).run();await timeline(c.env.DB,row.id,"RESOLUTION_SET",`resolution-${time}`,true,{resolutionCode:parsed.data.resolutionCode});await audit(c,"case.resolve","case",c.req.param("caseNumber"),{resolutionCode:parsed.data.resolutionCode});return data(c,{ok:true})});
app.delete("/api/v1/admin/cases/:caseNumber/resolution",async c=>{const row=await c.env.DB.prepare("SELECT id FROM cases WHERE case_number=? AND lifecycle_status='closed'").bind(c.req.param("caseNumber")).first<{id:number}>();if(!row)return error(c,409,"INVALID_TRANSITION","종료 사건이 아닙니다.");const published=await c.env.DB.prepare("SELECT 1 FROM patch_note_items i JOIN patch_notes p ON p.id=i.patch_note_id WHERE i.case_id=? AND p.status='published'").bind(row.id).first();if(published)return error(c,409,"PATCH_LOCKED","발행 패치노트 수록 사건은 재검토할 수 없습니다.");const time=now();await c.env.DB.prepare("UPDATE cases SET lifecycle_status='reviewing',resolution_code=NULL,official_comment=NULL,duplicate_of_case_id=NULL,resolved_at=NULL,updated_at=? WHERE id=?").bind(time,row.id).run();await timeline(c.env.DB,row.id,"CASE_REOPENED",`reopen-${time}`);await audit(c,"case.reopen","case",c.req.param("caseNumber"),{});return data(c,{ok:true})});

app.get("/api/v1/admin/patch-notes",async c=>{const rows=await c.env.DB.prepare("SELECT * FROM patch_notes ORDER BY created_at DESC,id DESC").all();return data(c,{items:rows.results.map(mapPatch),csrfToken:c.get("csrf")})});
app.post("/api/v1/admin/patch-notes",async c=>{const parsed=patchDraftSchema.safeParse(await c.req.json().catch(()=>null));if(!parsed.success)return error(c,400,"INVALID_BODY","제목과 slug를 확인하십시오.");const time=now();const row=await c.env.DB.prepare("INSERT INTO patch_notes (slug,title,introduction,created_at,updated_at) VALUES (?,?,?,?,?) RETURNING id").bind(parsed.data.slug,parsed.data.title,parsed.data.introduction,time,time).first<{id:number}>();await audit(c,"patch.create","patch",String(row?.id),{slug:parsed.data.slug});return data(c,{id:row?.id},201)});
app.get("/api/v1/admin/patch-notes/:id",async c=>{const note=await c.env.DB.prepare("SELECT * FROM patch_notes WHERE id=?").bind(c.req.param("id")).first<Record<string,any>>();if(!note)return error(c,404,"NOT_FOUND","패치노트를 찾지 못했습니다.");const items=await c.env.DB.prepare("SELECT c.case_number,c.title,i.section_code,i.editorial_note,i.display_order FROM patch_note_items i JOIN cases c ON c.id=i.case_id WHERE i.patch_note_id=? ORDER BY i.display_order").bind(note.id).all();const eligible=await c.env.DB.prepare("SELECT * FROM cases WHERE lifecycle_status='closed' AND visibility_status='public' AND resolution_code IN ('PATCHED','KNOWN_ISSUE','WORKS_AS_DESIGNED','WONT_FIX','CANNOT_REPRODUCE','ESCALATED_TO_UNIVERSE') ORDER BY resolved_at DESC").all();return data(c,{note:{...mapPatch(note),items:items.results.map(x=>({caseNumber:x.case_number,title:x.title,sectionCode:x.section_code,editorialNote:x.editorial_note,displayOrder:x.display_order}))},eligible:eligible.results.map(mapCase),csrfToken:c.get("csrf")})});
app.put("/api/v1/admin/patch-notes/:id/items",async c=>{const parsed=patchItemsSchema.safeParse(await c.req.json().catch(()=>null));if(!parsed.success)return error(c,400,"INVALID_BODY","수록 사건을 확인하십시오.");const note=await c.env.DB.prepare("SELECT status FROM patch_notes WHERE id=?").bind(c.req.param("id")).first<{status:string}>();if(!note||note.status!=="draft")return error(c,409,"PATCH_LOCKED","초안만 수록 사건을 변경할 수 있습니다.");const statements=[c.env.DB.prepare("DELETE FROM patch_note_items WHERE patch_note_id=?").bind(c.req.param("id"))];for(const item of parsed.data.items){const target=await c.env.DB.prepare("SELECT id,title,resolution_code FROM cases WHERE case_number=? AND lifecycle_status='closed' AND visibility_status='public'").bind(item.caseNumber).first<any>();if(!target||target.resolution_code!==item.sectionCode)return error(c,400,"INVALID_PATCH_ITEM",`${item.caseNumber}의 판정을 확인하십시오.`);statements.push(c.env.DB.prepare("INSERT INTO patch_note_items (patch_note_id,case_id,section_code,title_snapshot,editorial_note,display_order) VALUES (?,?,?,?,?,?)").bind(c.req.param("id"),target.id,item.sectionCode,target.title,item.editorialNote,item.displayOrder))}await c.env.DB.batch(statements);await audit(c,"patch.items","patch",c.req.param("id"),{count:parsed.data.items.length});return data(c,{ok:true})});
app.put("/api/v1/admin/patch-notes/:id/og-image",async c=>uploadOg(c,"patch"));
app.post("/api/v1/admin/patch-notes/:id/publish",async c=>{const note=await c.env.DB.prepare("SELECT id,status FROM patch_notes WHERE id=?").bind(c.req.param("id")).first<any>();if(!note||note.status!=="draft")return error(c,409,"INVALID_TRANSITION","초안만 발행할 수 있습니다.");const og=await c.env.DB.prepare("SELECT 1 FROM og_assets WHERE patch_note_id=?").bind(note.id).first();const count=await c.env.DB.prepare("SELECT COUNT(*) AS count FROM patch_note_items WHERE patch_note_id=?").bind(note.id).first<{count:number}>();if(!og||!(count?.count))return error(c,409,"PUBLISH_REQUIREMENTS","OG 이미지와 수록 사건이 필요합니다.");const time=now();await c.env.DB.prepare("UPDATE patch_notes SET status='published',published_at=?,updated_at=? WHERE id=?").bind(time,time,note.id).run();const cases=await c.env.DB.prepare("SELECT case_id FROM patch_note_items WHERE patch_note_id=?").bind(note.id).all();for(const item of cases.results)await timeline(c.env.DB,Number(item.case_id),"PATCH_NOTE_PUBLISHED",`patch-${note.id}`,true,{patchNoteId:note.id});await audit(c,"patch.publish","patch",String(note.id),{count:count.count});return data(c,{ok:true})});

async function uploadOg(c:any,type:"case"|"patch"){const length=Number(c.req.header("content-length")??0);if(c.req.header("content-type")!=="image/jpeg"||length>350000)return error(c,413,"INVALID_IMAGE","350KB 이하 JPEG만 허용됩니다.");const bytes=await c.req.arrayBuffer();if(bytes.byteLength<100||bytes.byteLength>350000)return error(c,413,"INVALID_IMAGE","이미지 크기를 확인하십시오.");const magic=new Uint8Array(bytes.slice(0,3));if(magic[0]!==0xff||magic[1]!==0xd8||magic[2]!==0xff)return error(c,400,"INVALID_IMAGE","JPEG 형식이 아닙니다.");let ownerId:number;if(type==="case"){const row=await c.env.DB.prepare("SELECT id FROM cases WHERE case_number=?").bind(c.req.param("caseNumber")).first<{id:number}>();if(!row)return error(c,404,"NOT_FOUND","사건을 찾지 못했습니다.");ownerId=row.id;await c.env.DB.prepare("DELETE FROM og_assets WHERE case_id=?").bind(ownerId).run();await c.env.DB.prepare("INSERT INTO og_assets (case_id,mime_type,byte_size,sha256,data,created_at) VALUES (?,'image/jpeg',?,?,?,?)").bind(ownerId,bytes.byteLength,await sha(bytes),bytes,now()).run()}else{ownerId=Number(c.req.param("id"));await c.env.DB.prepare("DELETE FROM og_assets WHERE patch_note_id=?").bind(ownerId).run();await c.env.DB.prepare("INSERT INTO og_assets (patch_note_id,mime_type,byte_size,sha256,data,created_at) VALUES (?,'image/jpeg',?,?,?,?)").bind(ownerId,bytes.byteLength,await sha(bytes),bytes,now()).run()}await audit(c,`${type}.og`,type,String(ownerId),{bytes:bytes.byteLength});return data(c,{ok:true})}

app.notFound(c=>error(c,404,"NOT_FOUND","관리 경로를 찾지 못했습니다."));app.onError((e,c)=>{console.error(JSON.stringify({requestId:c.get("requestId"),route:c.req.routePath,error:e.name}));return error(c,500,"INTERNAL_ERROR","관제 처리 중 오류가 발생했습니다.")});
export default{async fetch(request:Request,env:Env,ctx:ExecutionContext){const url=new URL(request.url);if(url.pathname.startsWith("/api/"))return app.fetch(request,env,ctx);const auth=await app.fetch(new Request(new URL("/api/v1/admin/health",request.url),{headers:request.headers}),env,ctx);if(!auth.ok)return auth;const asset=await env.ASSETS.fetch(request);const response=new Response(asset.body,asset);response.headers.set("X-Content-Type-Options","nosniff");response.headers.set("Referrer-Policy","no-referrer");response.headers.set("X-Robots-Tag","noindex, nofollow");response.headers.set("Content-Security-Policy","default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; base-uri 'none'; frame-ancestors 'none'");return response}} satisfies ExportedHandler<Env>;
