import { FormEvent, useEffect, useRef, useState } from "react";
import { Link, NavLink, Route, Routes, useLocation, useParams } from "react-router-dom";
import { api, getPublicConfig, getTurnstileToken } from "./api";
import { reproductionBand, resolutionLabels, type ResolutionCode } from "@hbc/shared";

type Analysis = { department: string; initialGrade: string; workaround: string; expectedVersion: string; bureaucracyWasteIndex: number };
type CaseSummary = { caseNumber: string; title: string; lifecycleStatus: string; resolutionCode: ResolutionCode | null; reproductionCount: number; publishedAt: string };
type CaseDetail = CaseSummary & { reproductionSteps: string; expectedResult: string; actualResult: string; environment: string; category: string | null; severity: string | null; evidenceEmoji: string | null; officialComment: string | null; analysis: Analysis; timeline: Array<{ eventType: string; createdAt: string; metadata: Record<string, unknown> }> };
type PatchNote = { id: number; slug: string; title: string; introduction: string; publishedAt: string; itemCount?: number; sections?: Array<{ code: ResolutionCode; label: string; items: Array<{ caseNumber: string; title: string; editorialNote: string }> }> };

function ScrollToTop() {
  const { pathname } = useLocation();
  useEffect(() => { window.scrollTo({ top: 0, left: 0, behavior: "instant" }); }, [pathname]);
  return null;
}

function Toast({ message }: { message: string }) {
  return message ? <div className="toast" role="status" aria-live="polite">{message}</div> : null;
}

function Dust({ small = false }: { small?: boolean }) {
  return <div className={`dust ${small ? "dust-small" : ""}`} aria-label="수습 관제관 먼지" role="img">
    <span className="antenna"/><span className="eye left"/><span className="eye right"/><span className="mouth"/>{!small && <span className="clipboard">HBC<br/><i>검토중</i></span>}
  </div>;
}

function Layout({ children }: { children: React.ReactNode }) {
  return <><header className="topbar"><Link to="/" className="brand"><Dust small/><span>인류 버그 센터</span></Link><nav><NavLink to="/bugs">사건</NavLink><NavLink to="/patch-notes">패치노트</NavLink><Link className="nav-report" to="/report">버그 신고</Link></nav></header><main>{children}</main><footer><span className="scribble">〰</span><b>인류는 아직 베타 버전입니다.</b><p>개인정보와 특정 인간의 신상은 입력하지 마십시오. 모든 판정은 본 서비스 세계관 안의 기록입니다.</p></footer></>;
}

function StatusChip({ lifecycle, resolution }: { lifecycle: string; resolution: ResolutionCode | null }) {
  const label = resolution ? resolutionLabels[resolution] : lifecycle === "reviewing" ? "검토 중" : lifecycle === "closed" ? "종료" : "접수됨";
  return <span className={`chip ${resolution ? "resolved" : lifecycle}`}>{label}</span>;
}

function CaseCard({ item }: { item: CaseSummary }) {
  return <Link className="case-card" to={`/bugs/${item.caseNumber}`}><div className="case-meta"><span>{item.caseNumber}</span><StatusChip lifecycle={item.lifecycleStatus} resolution={item.resolutionCode}/></div><h3>{item.title}</h3><div className="count-row"><b>{item.reproductionCount}명</b><span>동일 현상 재현</span><span className="arrow">→</span></div></Link>;
}

function Home() {
  const [data, setData] = useState<{ bugs: CaseSummary[]; patchNote: PatchNote | null }>({ bugs: [], patchNote: null });
  useEffect(() => { api<typeof data>("/api/v1/home").then(setData).catch(() => undefined); }, []);
  return <Layout><section className="hero"><div className="hero-copy"><p className="eyebrow">HUMAN BUG CENTER · 우주 관제 1인 부서</p><h1>인류는 아직<br/><em>베타 버전</em>입니다.</h1><p className="lead">일상에서 반복되는 인류의 이상 현상을 버그처럼 신고하십시오. 수습 관제관 먼지가 엄숙하게 접수합니다.</p><div className="hero-actions"><Link className="button primary" to="/report">버그 신고하기</Link><Link className="button ghost" to="/bugs">공개 사건 보기</Link></div><div className="trust"><span>✓ 회원가입 없음</span><span>✓ 파일 업로드 없음</span><span>✓ IP 저장 없음</span></div></div><div className="hero-dust"><div className="orbit">✦</div><Dust/><div className="memo"><span>관제 메모 07-13</span><b>현실 수정 권한:</b><strong>거의 없음</strong></div></div></section><section className="section"><div className="section-head"><div><p className="eyebrow">RECENT CASES</p><h2>최근 접수된 인류 결함</h2></div><Link to="/bugs">전체 사건 →</Link></div>{data.bugs.length ? <div className="case-grid">{data.bugs.map(x => <CaseCard item={x} key={x.caseNumber}/>)}</div> : <Empty message="아직 공개된 사건이 없습니다. 최초 신고가 행정적으로 기다려지고 있습니다."/>}</section><section className="loop-section"><div><p className="eyebrow">PROCESS</p><h2>발견에서 판정까지</h2></div><ol className="loop"><li><b>01</b><span>이상 현상<br/><strong>신고</strong></span></li><li><b>02</b><span>다른 인간의<br/><strong>재현 확인</strong></span></li><li><b>03</b><span>관제관의<br/><strong>공식 판정</strong></span></li><li><b>04</b><span>인류 OS<br/><strong>패치노트</strong></span></li></ol></section><section className="dust-quote"><Dust small/><blockquote>“개인적인 불운으로 종결하기 어려운 단계입니다.”</blockquote><span>— 수습 관제관 먼지</span></section></Layout>;
}

function Empty({ message }: { message: string }) { return <div className="empty"><span>⋯</span><p>{message}</p></div>; }

function Report() {
  const [botContext, setBotContext] = useState(""); const [loading, setLoading] = useState(false); const [error, setError] = useState(""); const [toast, setToast] = useState(""); const [result, setResult] = useState<{ caseNumber: string; accessToken: string; statusUrl: string; analysis: Analysis } | null>(null); const turnstile = useRef<HTMLDivElement>(null);
  useEffect(() => { api<{ token: string }>("/api/v1/bot-context", { method: "POST", body: JSON.stringify({ purpose: "report" }) }).then(x => setBotContext(x.token)).catch(e => setError(e.message)); }, []);
  useEffect(() => { if (!toast) return; const timer = window.setTimeout(() => setToast(""), 2400); return () => window.clearTimeout(timer); }, [toast]);
  async function copySecretLink() {
    await navigator.clipboard.writeText(`${location.origin}${result?.statusUrl ?? ""}`);
    if (window.matchMedia("(min-width: 761px)").matches) setToast("복사되었습니다");
  }
  async function submit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); setLoading(true); setError("");
    try {
      const form = new FormData(event.currentTarget); const config = await getPublicConfig(); const token = await getTurnstileToken(turnstile.current!, config.turnstileReportSiteKey, "report");
      const payload = Object.fromEntries(form); const created = await api<typeof result & object>("/api/v1/submissions", { method: "POST", body: JSON.stringify({ ...payload, submissionRequestId: crypto.randomUUID(), publicReviewConsent: form.get("publicReviewConsent") === "on", botContext, turnstileToken: token, severity: form.get("severity") || null, category: form.get("category") || null, evidenceEmoji: form.get("evidenceEmoji") || null }) }); setResult(created);
    } catch (e) { setError(e instanceof Error ? e.message : "접수에 실패했습니다."); } finally { setLoading(false); }
  }
  if (result) return <Layout><section className="narrow completion"><div className="stamp">접수 완료</div><p className="eyebrow">CASE CREATED</p><h1>{result.caseNumber}</h1><p>사건 번호가 발급되었습니다. 개인적인 불운으로 단정하기에는 행정 절차가 시작되었습니다.</p><AnalysisPanel data={result.analysis}/><div className="secret-box"><b>비밀 상태 링크</b><code>{location.origin}{result.statusUrl}</code><button className="button primary" onClick={copySecretLink}>링크 복사</button><small>계정과 이메일을 수집하지 않아 분실 시 복구할 수 없습니다.</small></div></section><Toast message={toast}/></Layout>;
  return <Layout><section className="narrow report-head"><p className="eyebrow">NEW BUG REPORT</p><h1>인류 버그 신고</h1><p>발견한 현상을 사실대로 기록하십시오. 농담 여부와 관계없이 모든 항목은 공식 업무로 처리됩니다.</p></section><form className="report-form" onSubmit={submit}><div className="privacy-banner"><b>개인정보 입력 금지</b><span>실명, 연락처, 주소, 직장·학교 등 특정 인간을 식별할 내용은 삭제한 뒤 제출하십시오.</span></div><label><span>버그 제목 <i>필수</i></span><input className="input" name="title" required minLength={3} maxLength={80} placeholder="예: 누우면 갑자기 오늘의 실수가 전부 재생됨"/></label><label><span>재현 단계 <i>필수</i></span><textarea className="textarea" name="reproductionSteps" required minLength={5} maxLength={1000} rows={5} placeholder={'1. 하루를 평범하게 보낸다\n2. 잠자리에 눕는다\n3. 8년 전 실수가 자동 재생된다'}/></label><div className="two-col"><label><span>기대한 결과 <i>필수</i></span><textarea className="textarea" name="expectedResult" required minLength={2} maxLength={500} rows={4} placeholder="평온하게 잠든다"/></label><label><span>실제 결과 <i>필수</i></span><textarea className="textarea" name="actualResult" required minLength={2} maxLength={500} rows={4} placeholder="이불을 발로 차며 각성한다"/></label></div><details><summary>선택 정보 추가 <span>환경 · 심각도 · 분류</span></summary><div className="optional-grid"><label><span>발생 환경</span><input className="input" name="environment" maxLength={120} placeholder="예: 취침 직전, 지하철, 회의 중"/></label><label><span>체감 심각도</span><select className="select" name="severity" defaultValue=""><option value="">선택 안 함</option><option value="minor">사소함</option><option value="annoying">불편함</option><option value="serious">심각함</option><option value="critical">치명적으로 느껴짐</option></select></label><label><span>분류</span><select className="select" name="category" defaultValue=""><option value="">선택 안 함</option><option value="communication">소통</option><option value="habit">습관</option><option value="work">업무·학업</option><option value="relationship">관계</option><option value="body_mind">몸·마음</option><option value="society">사회 시스템</option><option value="other">기타</option></select></label><label><span>증거 이모지</span><select className="select" name="evidenceEmoji" defaultValue=""><option value="">선택 안 함</option>{["🫠","🤦","🙃","😵‍💫","🫥","🤔"].map(x => <option key={x}>{x}</option>)}</select></label></div></details><label className="honeypot" aria-hidden="true">웹사이트<input className="input" name="website" tabIndex={-1} autoComplete="off"/></label><label className="consent"><input className="checkbox" type="checkbox" name="publicReviewConsent" required/><span>개인정보를 제거했으며, 운영자 검토 후 이 신고가 공개 사건으로 게시되는 데 동의합니다.</span></label><div ref={turnstile}/>{error && <p className="error" role="alert">{error}</p>}<button className="button primary submit" disabled={loading || !botContext}>{loading ? "사람 여부와 행정 서류를 확인하는 중…" : "사건 번호 발급받기"}</button><p className="form-note">평균 접수 시간 1분 · 사진과 파일은 받지 않습니다.</p></form></Layout>;
}

function AnalysisPanel({ data }: { data: Analysis }) { return <section className="analysis"><div className="section-head"><div><p className="eyebrow">AUTOMATED TRIAGE · V1</p><h2>규칙 기반 사전 분석</h2></div><span className="analysis-badge">통계 아님</span></div><dl><div><dt>임시 담당 부서</dt><dd>{data.department}</dd></div><div><dt>초기 행정 등급</dt><dd>{data.initialGrade}</dd></div><div className="wide"><dt>임시 해결책</dt><dd>{data.workaround}</dd></div><div><dt>예상 수정 버전</dt><dd>{data.expectedVersion}</dd></div><div><dt>행정력 낭비 지수</dt><dd>{data.bureaucracyWasteIndex}/100</dd></div></dl><small>사건 번호로 생성된 행정용 문구이며 실제 통계나 해결 약속이 아닙니다.</small></section>; }

function Bugs() { const [items, setItems] = useState<CaseSummary[]>([]); const [error, setError] = useState(""); useEffect(() => { api<{ items: CaseSummary[] }>("/api/v1/bugs").then(x => setItems(x.items)).catch(e => setError(e.message)); }, []); return <Layout><section className="page-head"><p className="eyebrow">PUBLIC INCIDENTS</p><h1>공개 사건 기록</h1><p>다른 인간에게도 동일하게 발생하는지 확인 중인 현상입니다.</p></section><section className="section">{error ? <p className="error">{error}</p> : items.length ? <div className="case-grid">{items.map(x => <CaseCard item={x} key={x.caseNumber}/>)}</div> : <Empty message="공개 승인된 사건이 없습니다."/>}</section></Layout>; }

function BugDetail() {
  const { caseNumber = "" } = useParams(); const [item, setItem] = useState<CaseDetail | null>(null); const [error, setError] = useState(""); const [busy, setBusy] = useState(false); const turnstile = useRef<HTMLDivElement>(null);
  useEffect(() => { api<CaseDetail>(`/api/v1/bugs/${caseNumber}`).then(setItem).catch(e => setError(e.message)); }, [caseNumber]);
  async function reproduce() { setBusy(true); setError(""); try { const context = await api<{ token: string }>("/api/v1/bot-context", { method: "POST", body: JSON.stringify({ purpose: "reproduce", caseNumber }) }); const config = await getPublicConfig(); const token = await getTurnstileToken(turnstile.current!, config.turnstileReproduceSiteKey, "reproduce"); const result = await api<{ reproductionCount: number; alreadyReported: boolean }>(`/api/v1/bugs/${caseNumber}/reproductions`, { method: "POST", body: JSON.stringify({ botContext: context.token, turnstileToken: token }) }); setItem(x => x ? { ...x, reproductionCount: result.reproductionCount } : x); if (result.alreadyReported) setError("이 브라우저에서는 이미 동일 현상을 보고했습니다."); } catch (e) { setError(e instanceof Error ? e.message : "재현 보고에 실패했습니다."); } finally { setBusy(false); } }
  if (error && !item) return <NotFound message={error}/>; if (!item) return <Layout><Empty message="사건 기록을 조회하는 중입니다."/></Layout>;
  return <Layout><article className="bug-detail"><div className="bug-title"><div className="case-meta"><span>{item.caseNumber}</span><StatusChip lifecycle={item.lifecycleStatus} resolution={item.resolutionCode}/></div><h1>{item.title}</h1><div className="repro-box"><div><strong>{item.reproductionCount}</strong><span>명의 인간이 재현함</span><p>{reproductionBand(item.reproductionCount)}</p></div><button className="button primary" onClick={reproduce} disabled={busy}>{busy ? "확인 중…" : "나도 재현됨"}</button><div className="turnstile-slot" ref={turnstile}/></div>{error && <p className="notice">{error}</p>}</div><div className="report-content"><section><p className="eyebrow">REPRODUCTION</p><h2>재현 단계</h2><p className="preline">{item.reproductionSteps}</p></section><div className="two-col"><section><p className="eyebrow">EXPECTED</p><h2>기대한 결과</h2><p>{item.expectedResult}</p></section><section><p className="eyebrow coral">ACTUAL</p><h2>실제 결과</h2><p>{item.actualResult}</p></section></div></div><AnalysisPanel data={item.analysis}/>{item.resolutionCode && <section className="verdict"><div className="stamp small">공식 판정</div><p>{resolutionLabels[item.resolutionCode]}</p><h2>{item.officialComment}</h2><Dust small/></section>}<section className="timeline"><p className="eyebrow">CASE HISTORY</p><h2>사건 타임라인</h2>{item.timeline.map((event, i) => <div className="timeline-row" key={i}><span/><time>{new Date(event.createdAt).toLocaleDateString("ko-KR")}</time><b>{eventLabel(event.eventType)}</b></div>)}</section><ShareButton title={item.title}/></article></Layout>;
}

function eventLabel(type: string) { return ({ SUBMITTED: "사건이 접수되었습니다.", PREANALYSIS_COMPLETED: "사전 분석이 완료되었습니다.", PUBLIC_APPROVED: "공개 사건으로 승인되었습니다.", PUBLIC_HIDDEN: "공개가 중단되었습니다.", PUBLIC_RESTORED: "공개가 복원되었습니다.", REPRODUCTION_THRESHOLD_REACHED: "재현 보고가 새로운 단계에 도달했습니다.", REVIEW_STARTED: "운영자 검토가 시작되었습니다.", REVIEW_RETURNED_TO_OPEN: "추가 관찰 상태로 돌아갔습니다.", RESOLUTION_SET: "공식 판정이 등록되었습니다.", CASE_REOPENED: "사건이 재검토 대상으로 전환되었습니다.", PATCH_NOTE_PUBLISHED: "인류 OS 패치노트에 수록되었습니다." } as Record<string,string>)[type] ?? type; }
function ShareButton({ title }: { title: string }) { const [toast, setToast] = useState(""); useEffect(() => { if (!toast) return; const timer = window.setTimeout(() => setToast(""), 2400); return () => window.clearTimeout(timer); }, [toast]); async function share() { if (navigator.share) await navigator.share({ title, text: "인류 버그 센터 사건 기록", url: location.href }); else { await navigator.clipboard.writeText(location.href); setToast("복사되었습니다"); } } return <><button className="button ghost share" onClick={share}>사건 공유하기</button><Toast message={toast}/></>; }

function PatchList() { const [items, setItems] = useState<PatchNote[]>([]); useEffect(() => { api<{ items: PatchNote[] }>("/api/v1/patch-notes").then(x => setItems(x.items)).catch(() => undefined); }, []); return <Layout><section className="page-head patch-head"><p className="eyebrow">HUMAN OS RELEASE NOTES</p><h1>인류 OS 패치노트</h1><p>수습 관제관이 수동으로 정리한 공식 판정 기록입니다.</p></section><section className="section">{items.length ? <div className="patch-list">{items.map(x => <Link to={`/patch-notes/${x.slug}`} key={x.slug}><time>{new Date(x.publishedAt).toLocaleDateString("ko-KR")}</time><h2>{x.title}</h2><p>{x.introduction}</p><span>{x.itemCount}개 사건 수록 →</span></Link>)}</div> : <Empty message="발행된 패치노트가 없습니다. 자동 발행 계획도 없습니다."/>}</section></Layout>; }
function PatchDetail() { const { slug = "" } = useParams(); const [note, setNote] = useState<PatchNote | null>(null); useEffect(() => { api<PatchNote>(`/api/v1/patch-notes/${slug}`).then(setNote).catch(() => undefined); }, [slug]); if (!note) return <NotFound message="패치노트를 찾지 못했습니다."/>; return <Layout><article className="patch-detail"><p className="eyebrow">HUMAN OS RELEASE NOTES</p><h1>{note.title}</h1><time>{new Date(note.publishedAt).toLocaleDateString("ko-KR")}</time><p className="intro">{note.introduction}</p>{note.sections?.map(section => <section key={section.code}><div className="section-head"><h2>{section.label}</h2><span>{section.items.length}</span></div>{section.items.map(item => <Link className="patch-item" to={`/bugs/${item.caseNumber}`} key={item.caseNumber}><b>{item.caseNumber}</b><h3>{item.title}</h3>{item.editorialNote && <p>{item.editorialNote}</p>}</Link>)}</section>)}<Dust/><ShareButton title={note.title}/></article></Layout>; }

function SubmissionStatus() { const { accessToken = "" } = useParams(); const [data, setData] = useState<(CaseDetail & { moderationStatus: string; visibilityStatus: string; moderationNote: string | null }) | null>(null); const [error, setError] = useState(""); useEffect(() => { api<typeof data & object>("/api/v1/submissions/status", { method: "POST", body: JSON.stringify({ accessToken }) }).then(setData).catch(e => setError(e.message)); }, [accessToken]); if (!data) return <NotFound message={error || "비밀 사건 기록을 조회하는 중입니다."}/>; return <Layout><section className="narrow status-page"><p className="eyebrow">PRIVATE CASE STATUS</p><h1>{data.caseNumber}</h1><div className="status-banner"><StatusChip lifecycle={data.lifecycleStatus} resolution={data.resolutionCode}/><b>{data.moderationStatus === "pending" ? "공개 검토 대기 중" : data.moderationStatus === "rejected" ? "공개 반려" : data.visibilityStatus === "hidden" ? "공개 중단" : "공개 승인"}</b></div>{data.moderationNote && <p className="notice">{data.moderationNote}</p>}<h2>{data.title}</h2><AnalysisPanel data={data.analysis}/>{data.visibilityStatus === "public" && <Link className="button primary" to={`/bugs/${data.caseNumber}`}>공개 사건 보기</Link>}<p className="form-note">이 페이지의 주소는 사건 조회 권한입니다. 공개적으로 공유하지 마십시오.</p></section></Layout>; }
function NotFound({ message = "요청한 기록을 찾지 못했습니다." }: { message?: string }) { return <Layout><section className="not-found"><Dust/><p className="eyebrow">404 · RECORD NOT FOUND</p><h1>{message}</h1><p>미공개, 숨김 또는 존재하지 않는 사건은 동일하게 처리됩니다.</p><Link className="button primary" to="/">관제실로 돌아가기</Link></section></Layout>; }

export function App() { return <><ScrollToTop/><Routes><Route path="/" element={<Home/>}/><Route path="/report" element={<Report/>}/><Route path="/bugs" element={<Bugs/>}/><Route path="/bugs/:caseNumber" element={<BugDetail/>}/><Route path="/patch-notes" element={<PatchList/>}/><Route path="/patch-notes/:slug" element={<PatchDetail/>}/><Route path="/submissions/:accessToken" element={<SubmissionStatus/>}/><Route path="*" element={<NotFound/>}/></Routes></>; }
